version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3