version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - DEBUG=pinia*
      - VUE_APP_API_RETRY_DELAY=1000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    volumes:
      - ./src:/app/src:ro